// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFd3Hl_SU8qHwxtgaQWpC6JU7vQIibWoE',
    appId: '1:458447359335:android:e03291592ae4c9e26173c2',
    messagingSenderId: '458447359335',
    projectId: 'uni-app-74ade',
    storageBucket: 'uni-app-74ade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcPjND3jA2gAnlCOxPANMX9wIF5cvDrlo',
    appId: '1:458447359335:ios:88eb2f20440fdcfd6173c2',
    messagingSenderId: '458447359335',
    projectId: 'uni-app-74ade',
    storageBucket: 'uni-app-74ade.appspot.com',
    iosClientId: '458447359335-6ge9upqahng950i2tpjkmd7vjjplti4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.uni',
  );
}
